# Generated by Django 4.2.9 on 2024-02-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProdavnicaBilijara', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='category',
            index_together={('id', 'slug')},
        ),
    ]
