# Generated by Django 4.2.9 on 2024-02-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProdavnicaBilijara', '0002_alter_category_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='category',
            index_together=set(),
        ),
    ]
